---
- name: check .ok file in salve
  wait_for:
    path: "{{ slave_path_mds_home_data_flags }}/{{ item }}"
    state: present
    timeout: 1
  with_items:
    - "{{ fetch_sse_ok }}"
    - "{{ fetch_szse_ok }}"
    - "{{ fetch_mon_ok }}"
  ignore_errors: yes
  register: flag_res