---
#cron_job_name: "bse_collector"
#cron_chinese_name: "上海产品数据获取"
#cron_job_start_hour: "{{ bse_start_hour }}"
#cron_job_start_minute: "{{ bse_start_minute }}"
#cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/bse.sh'

cron_job_name: "{{ get_bse_name }}"
cron_chinese_name: "{{ get_bse_ch_name }}"
cron_job_start_hour: "{{ bse_start_hour }}"
cron_job_start_minute: "{{ bse_start_minute }}"
cron_job_action: "{{ get_bse_action }}"

success_cmd: "./mds taskstatus -k DATA_FETCH_BSE -S 5 -m ''"
failed_cmd: "./mds taskstatus -k DATA_FETCH_BSE -S 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./mds taskstatus -k DATA_FETCH_BSE -S 4 -m '获取数据失败, 需人工干预'"

fetch_ok_flag: "{{ fetch_bse_ok }}"
task_end_time: "{{ bse_end_time }}"
art_run_once: "{{ bse_run_once }}"