---

- name: clear bse directory
  shell: "cd {{ ansible_path_files_bse }} && rm -rf *"
  delegate_to: 127.0.0.1
  run_once: true

- name: fetch remote bse file
  shell: python3 run_command.py "rsync -az --no-r -e 'ssh -p {{ ssh_port }}' {{ bse_user }}@{{ bse_host }}:{{ gateway_path_root_bse }}/{{ item }} {{ ansible_path_files_bse }}/"
  args:
    chdir: "{{ ansible_path_scripts_files }}"
  with_items: "{{ bse_cp_files_list }}"
  ignore_errors: yes
  delegate_to: 127.0.0.1
  run_once: yes