---

#- name: send bse file to mds
# copy:
#    src: "{{ item }}"
#    dest: "{{ slave_path_mds_home_data_exchange }}"
#    owner: "{{ mdsuser }}"
#    group: "{{ mdsuser }}"
#    mode: 0644
#  with_fileglob: "{{ ansible_path_files_bse }}/*"
#  ignore_errors: yes


- name: send bse etf security files
  synchronize:
    src: "{{ ansible_path_files_bse }}/"
    dest: "{{ slave_path_mds_home_data_exchange }}"
    checksum: yes
  register: collector_bse_files_result
  ignore_errors: yes