---
#- name: check csdc files ready
#  wait_for:
#    path: "{{ slave_path_oes_home_data_csdc }}/{{item}}"
#    state: present
#    timeout: 1
#  with_items: "{{ csdc_check_files }}"
#  register: check_result
#  ignore_errors: True

- name: check csdc files ready
  find:
    paths: "{{ slave_path_oes_home_data_csdc }}"
    get_checksum: yes
    file_type: file
    use_regex: yes
    patterns: "{{ item }}"
  with_items: "{{ csdc_check_files }}"
  register: find_res

- name: print csdc files ready
  debug:
    msg: "file ==> {{ item.item }} | matched ==> {{ item.matched }}"
  failed_when: "item.matched == 0"
  with_items: "{{ find_res.results }}"
  loop_control:
    label: "{{ item.item }}"
  ignore_errors: yes
  register: check_result

- name: send csdc files ready to mon
  command: "{{ python3 }} mon_log.py -c 'no such file: {{ item.item }}' >> /dev/null"
  args:
    chdir: "{{ ansible_path_scripts_files }}"
  when: "item.matched == 0"
  with_items: "{{ find_res.results }}"
  loop_control:
    label: "{{ item.item }}"
  delegate_to: 127.0.0.1
  ignore_errors: yes
  run_once: yes
