---
cron_job_name: "{{ get_csdc_name }}"
cron_chinese_name: "{{ get_csdc_ch_name }}"
cron_job_start_hour: "{{ csdc_start_hour }}"
cron_job_start_minute: "{{ csdc_start_minute }}"
cron_job_action: "{{ get_csdc_action }}"

running_cmd: "./oes taskstatus -k DATA_FETCH_SDC -S 2"
success_cmd: "./oes taskstatus -k DATA_FETCH_SDC -S 5 -m ''"
failed_cmd: "./oes taskstatus -k DATA_FETCH_SDC 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./oes taskstatus -k DATA_FETCH_SDC -S 4 -m '获取数据失败, 需人工干预'"

task_end_time: "{{ csdc_end_time }}"
fetch_ok_flag: "{{ fetch_csdc_ok }}"
art_run_once: "{{ csdc_run_once }}"
remote_files: []
counter_files: []
