---
cron_job_name: "{{ get_mon_name }}"
cron_chinese_name: "{{ get_mon_ch_name }}"
cron_job_start_hour: "{{ mon_start_hour }}"
cron_job_start_minute: "{{ mon_start_minute }}"
cron_job_action: "{{ get_mon_action }}"

running_cmd: "./oes taskstatus -k DATA_FETCH_MON -S 2"
success_cmd: "./oes taskstatus -k DATA_FETCH_MON -S 5 -m ''"
failed_cmd: "./oes taskstatus -k DATA_FETCH_MON -S 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./oes taskstatus -k DATA_FETCH_MON -S 4 -m '获取数据失败, 需人工干预'"

task_end_time: "{{ mon_end_time }}"
fetch_ok_flag: "{{ fetch_mon_ok }}"
art_run_once: "{{ mon_run_once }}"
