---
cron_job_name: "{{ get_conf_name }}"
cron_chinese_name: "{{ get_conf_ch_name }}"
cron_job_start_hour: "{{ conf_start_hour }}"
cron_job_start_minute: "{{ conf_start_minute }}"
cron_job_action: "{{ get_conf_action }}"

success_cmd: "./mds taskstatus -k DATA_FETCH_CFG -S 5 -m ''"
failed_cmd: "./mds taskstatus -k DATA_FETCH_CFG 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./mds taskstatus -k DATA_FETCH_CFG -S 4 -m '获取数据失败, 需人工干预'"

task_end_time: "{{ conf_end_time }}"
fetch_ok_flag: "{{ fetch_conf_ok }}"
art_run_once: "{{ conf_run_once }}"
