---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ../../../automatic.yml

  tasks:
    - include: ../common/get_time.yml

    - block:
      - include: ./load/mds_checker.yml

      - include: ./load/mds_load.yml
        when: check_result is success
