---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ./reset/mds_reset_vars.yml
    - ../../../automatic.yml

  handlers:
    - include: ../common/crontab_handlers.yml

  tasks:
    - include: ../common/get_time.yml

    - block:

      - include: ./reset/mds_reset.yml

      when: disable_mds_reset == false




