---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ../../../automatic.yml

  tasks:
    - name: ping all host
      ping:
      register: ping_res

    - name: print ping_res
      debug:
        msg: "{{ ping_res }}"