---
cron_job_name: "stop_mds"
cron_chinese_name: "行情系统关闭"
cron_job_start_hour: "{{ cron_job_mds_stop_time_hh }}"
cron_job_start_minute: "{{ cron_job_mds_stop_time_mm }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/stop.sh'