---
cron_job_name: "{{ get_szse_name }}"
cron_chinese_name: "{{ get_szse_ch_name }}"
cron_job_start_hour: "{{ szse_start_hour }}"
cron_job_start_minute: "{{ szse_start_minute }}"
cron_job_action: "{{ get_szse_action }}"

running_cmd: "./oes taskstatus -k DATA_FETCH_SZSE -S 2"
success_cmd: "./oes taskstatus -k DATA_FETCH_SZSE -S 5 -m ''"
failed_cmd: "./oes taskstatus -k DATA_FETCH_SZSE -S 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./oes taskstatus -k DATA_FETCH_SZSE -S 4 -m '获取数据失败, 需人工干预'"

task_end_time: "{{ szse_end_time }}"
fetch_ok_flag: "{{ fetch_szse_ok }}"
art_run_once: "{{ szse_run_once }}"
