---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ./oes_backup_vars.yml
    - ../../../automatic.yml

  handlers:
    - include: ../common/crontab_handlers.yml

  tasks:
    - include: ../common/get_time.yml

    - block:
      - include: ./oes_backup.yml

      - include: ./set_status.yml

      - include: ./oes_backup_register.yml

        when: not disable_oes_backup

    - include: ../common/after_playbook.yml






