---
cron_job_name: "mds_nakedstart"
cron_chinese_name: "行情系统裸启动"
cron_job_start_hour: "{{ cron_job_mds_nakedstart_time_hh }}"
cron_job_start_minute: "{{ cron_job_mds_nakedstart_time_mm }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/nakedstart.sh'

