---

- name: nakedstart master mds
  command: ./mds st -B
  args:
    chdir: "{{ slave_path_mds_home_bin }}"
  when: ansible_host==mds_master_hostname
  register: naked_start_master
  ignore_errors: yes

- name: nakedstart follow and arbiter mds
  command: ./mds st -B
  args:
    chdir: "{{ slave_path_mds_home_bin }}"
  when: ansible_host!=mds_master_hostname
  register: naked_start_other
  ignore_errors: yes




