---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ./bse_gateway/bse_vars.yml
    - ../../../automatic.yml

  handlers:
    - include: ../common/crontab_handlers.yml

  tasks:
    - include: ../common/get_time.yml

    - include: ../common/before_playbook.yml

    - block:
      - include: ./bse_gateway/gateway_to_local.yml

      - include: ./bse_gateway/local_to_mds.yml

      - include: ./bse_gateway/bse_checker.yml

      - include: ../common/set_status.yml

      - include: ../common/colct_register.yml

        when: disable_bse_collector == false

    - include: ../common/after_playbook.yml
