---
cron_job_name: "oes_open"
cron_chinese_name: "交易系统开工"
cron_job_start_hour: "{{ open_start_hour }}"
cron_job_start_minute: "{{ open_start_minute }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/open.sh'

cmd: "./oes open"


