---
- name: touch reset success
  file:
    path: "{{ ansible_flag }}/{{ flag_success }}"
    state: touch
  when: reset_res is success
  delegate_to: 127.0.0.1
  run_once: true

- name: touch reset retry
  file:
    path: "{{ ansible_flag }}/{{ flag_retry }}"
    state: touch
  when: reset_res is not success
  delegate_to: 127.0.0.1
  run_once: true