---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ../../../automatic.yml

  tasks:
    - include: ./oes_dep.yml

    - include: ./create_dir.yml

    - include: ./oes_cfg.yml


