---
#cron_job_name: "sse_collector"
#cron_chinese_name: "上海产品数据获取"
#cron_job_start_hour: "{{ sse_start_hour }}"
#cron_job_start_minute: "{{ sse_start_minute }}"
#cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/sse.sh'

cron_job_name: "{{ get_sse_name }}"
cron_chinese_name: "{{ get_sse_ch_name }}"
cron_job_start_hour: "{{ sse_start_hour }}"
cron_job_start_minute: "{{ sse_start_minute }}"
cron_job_action: "{{ get_sse_action }}"

success_cmd: "./mds taskstatus -k DATA_FETCH_SSE -S 5 -m ''"
failed_cmd: "./mds taskstatus -k DATA_FETCH_SSE -S 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./mds taskstatus -k DATA_FETCH_SSE -S 4 -m '获取数据失败, 需人工干预'"

fetch_ok_flag: "{{ fetch_sse_ok }}"
task_end_time: "{{ sse_end_time }}"
art_run_once: "{{ sse_run_once }}"