---
- name: get gzlx month
  raw: echo "obase=16;{{ curr_date[4:6] }}"|bc|tr '[A-Z]' '[a-z]'
  delegate_to: 127.0.0.1
  run_once: true
  register: gzlx_mm

#- name: check sse files ready
#  wait_for:
#    path: "{{ slave_path_mds_home_data_exchange }}/{{item}}"
#    state: present
#    timeout: 1
#  with_items: "{{ sse_check_files_list }}"
#  register: check_result
#  ignore_errors: yes

- name: check sse files ready
  find:
    paths: "{{ slave_path_mds_home_data_exchange }}"
    get_checksum: yes
    file_type: file
    use_regex: yes
    patterns: "{{ item }}"
  with_items: "{{ sse_check_files_list }}"
  register: find_res

- name: print sse files ready
  debug:
    msg: "file ==> {{ item.item }} | matched ==> {{ item.matched }}"
  failed_when: "item.matched == 0"
  with_items: "{{ find_res.results }}"
  loop_control:
    label: "{{ item.item }}"
  ignore_errors: yes
  register: check_result

- name: send sse files ready to mon
  command: "{{ python3 }} mon_log.py -c 'no such file: {{ item.item }}' >> /dev/null"
  args:
    chdir: "{{ ansible_path_scripts_files }}"
  when: "item.matched == 0"
  with_items: "{{ find_res.results }}"
  loop_control:
    label: "{{ item.item }}"
  ignore_errors: yes
  delegate_to: 127.0.0.1
  run_once: yes







