---

- name: touch close success
  file:
    path: "{{ ansible_flag }}/{{ flag_success }}"
    state: touch
  when: close_res is not failed and ansible_play_hosts == ansible_play_hosts_all
  delegate_to: 127.0.0.1
  run_once: true

- name: touch close failed
  file:
    path: "{{ ansible_flag }}/{{ flag_failed }}"
    state: touch
  when: close_res is failed or ansible_play_hosts != ansible_play_hosts_all
  delegate_to: 127.0.0.1
  run_once: true
