---

- name: nakedstart master oes
  command: "{{ cmd }}"
  args:
    chdir: "{{ slave_path_oes_home_bin }}"
  when: ansible_host==oes_master_hostname
  register: naked_start_master
  ignore_errors: yes

- name: nakedstart follow and arbiter oes
  command: "{{ cmd }}"
  args:
    chdir: "{{ slave_path_oes_home_bin }}"
  when: ansible_host!=oes_master_hostname
  register: naked_start_other
  ignore_errors: yes




