---

#- name: send mon file to mds
#  copy:
#    src: "{{ item }}"
#    dest: "{{ slave_path_mds_home_data_exchange }}"
#    owner: "{{ mdsuser }}"
#    group: "{{ mdsuser }}"
#    mode: 0644
#  with_fileglob: "{{ ansible_path_files_szse }}/*"
#  ignore_errors: yes

- name: send szse file to mds
  synchronize:
    src: "{{ ansible_path_files_szse }}/"
    dest: "{{ slave_path_mds_home_data_exchange }}"
    checksum: yes
  register: collector_szse_files_result
  ignore_errors: yes