---
cron_job_name: "oes_stop"
cron_chinese_name: "交易系统关闭"
cron_job_start_minute: "{{ stop_start_minute }}"
cron_job_start_hour: "{{ stop_start_hour }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/stop.sh'

cmd: "./oes sp -F"
