---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ./open/oes_open_vars.yml
    - ../../../automatic.yml

  handlers:
    - include: ../common/crontab_handlers.yml

  tasks:
    - include: ../common/get_time.yml

    - block:

      - include: ./open/oes_open.yml

      - include: ./open/site_status.yml
        when: cron_control_oes_enable

      when: not disable_oes_open

    - include: ../common/after_playbook.yml



