---
- hosts: all
  vars_files:
    - ../../../inventory/vars_files/common_vars.yml
    - ./thaw/oes_thaw_vars.yml
    - ../../../automatic.yml

  handlers:
    - include: ../common/crontab_handlers.yml

  tasks:
    - include: ../common/get_time.yml

    - block:

      - include: ./thaw/oes_thaw.yml

      when: not disable_oes_thaw

    - include: ../common/after_playbook.yml



