---

- name: check .ok file in salve
  wait_for:
    path: "{{ slave_path_oes_home_data_flags }}/{{ item }}"
    state: present
    timeout: 1
  when: "ansible_host!=oes_arbiter_hostname"
  with_items:
    - "{{ fetch_sse_ok }}"
    - "{{ fetch_szse_ok }}"
    - "{{ fetch_mon_ok }}"
    - "{{ fetch_counter_ok }}"
#    - "{{ fetch_csdc_ok }}"
    #- "{{ fetch_conf_ok }}"
  ignore_errors: yes
  register: check_result
