---
cron_job_name: "{{ get_sse_late_name }}"
cron_chinese_name: "{{ get_sse_late_ch_name }}"
cron_job_start_hour: "{{ sse_late_start_hour }}"
cron_job_start_minute: "{{ sse_late_start_minute }}"
cron_job_action: "{{ get_sse_late_action }}"

running_cmd: "./oes taskstatus -k DATA_FETCH_SSE -S 2"
success_cmd: "./oes taskstatus -k DATA_FETCH_SSE -S 5 -m ''"
failed_cmd: "./oes taskstatus -k DATA_FETCH_SSE -S 4 -m '获取数据失败, {{cron_job_cycles}}分钟后尝试重新拉取数据'"
timeout_cmd: "./oes taskstatus -k DATA_FETCH_SSE -S 4 -m '获取数据失败, 需人工干预'"

task_end_time: "{{ sse_late_end_time }}"
fetch_ok_flag: "{{ fetch_sse_late_ok }}"
art_run_once: "{{ sse_late_run_once }}"
