---
cron_job_name: "oes_write_back"
cron_chinese_name: "回写数据"
cron_job_start_hour: "{{ write_back_hour }}"
cron_job_start_minute: "{{ write_back_minute }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/write_back.sh'
