---
cron_job_name: "oes_shutoff"
cron_chinese_name: "交易系统下线"
cron_job_start_hour: "{{ cron_job_oes_shutoff_time_hh }}"
cron_job_start_minute: "{{ cron_job_oes_shutoff_time_mm }}"
cron_job_action: 'cd {{ ansible_path_ansible_home }} && sh cmd/shutoff.sh'

cmd: "./oes shutoff"

